name: appa-football-academy-web
services:
  web:
    container_name: appa-football-academy-web
    image: docker-reg1.appa-tech.com/football-academy/web:latest
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - SUPABASE_CONNECTION_STRING=${SUPABASE_CONNECTION_STRING}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SUPABASE_URL=${SUPABASE_URL}
        - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    restart: always
    ports:
      - 3000:3000
